### ISSUE TITLE
Chosing mod in game creating

### ISSUE THREAD

**Issue by Huymnsel** [Canthinkofaname/Greece-plus-The-Middle-East#7]
Even though "Locate mod errors" says "No problems found", the game still says there are bugs with Lydia's + Pontus' and Krypteia's + Macedonian Phalanx's uniques

**Comment by Canthinkofaname** [comment]
Should be fixed in the new update. Its due to mispellings of uniques such as ["+[10 [Production] ]"] is supposed to be ["[+10 [Production] ]"]
